flowchart TD
    A[requests\nОСНОВНОЙ ПАКЕТ]
    A --> B1[certifi\nПРЯМАЯ ЗАВИСИМОСТЬ]
    A --> B2[charset_normalizer\nПРЯМАЯ ЗАВИСИМОСТЬ]
    A --> B3[idna\nПРЯМАЯ ЗАВИСИМОСТЬ]
    A --> B4[urllib3\nПРЯМАЯ ЗАВИСИМОСТЬ]
